package:
  name: http-log
  epoch: 0
  version: v0.7.17-3-gea2a80b-dirty
  description: Logs HTTP requests
  url: https://github.com/mt-inside/http-log
  copyright:
    - paths:
        - "*"
      license: Apache-2.0
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - wolfi-base
      - build-base
      - go
      - just
      - git
pipeline:
  - name: Build
    runs: |
      git config --global --add safe.directory /home/build
      just build-ci -o "${{targets.destdir}}/usr/bin/http-log"
