package:
  name: http-log
  # TODO: take as arg or something
  version: 0.7.10
  description: Logs HTTP requests
  target-architecture: [all] # bails on a lot of them which aren't supported yet
  copyright:
    - paths: ["*"]
      licence: Apache-2.0

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - wolfi-base
      - build-base
      - go

pipeline:
  - name: Build
    runs: |
      # build, rather than install, to be able to control output dir
      CGO_ENABLED=0 go build -o "${{targets.destdir}}/usr/bin/http-log" -a -tags netgo -ldflags "-w -extldflags '-static' -X 'github.com/mt-inside/http-log/pkg/build.Version="${{package.version}}"'" ./cmd/http-log
